name: Setup Node.js
description: Setup Node.js with npm cache

inputs:
  node-version:
    description: Node.js version
    required: true
    default: '22'

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: npm
        cache-dependency-path: package-lock.json
